<?php
/**
*
* File: _admin/_inc/exercises/_liquibase/index_images.php
* Version 1.0.0
* Date 12:57 24.03.2021
* Copyright (c) 2021 Sindre Andre Ditlefsen
* License: http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/
/*- Access check ----------------------------------------------------------------------- */
if(!(isset($define_access_to_control_panel))){
	echo"<h1>Server error 403</h1>";
	die;
}

/*- Tables ---------------------------------------------------------------------------- */

$result = mysqli_query($link, "DROP TABLE IF EXISTS $t_exercise_index_images") or die(mysqli_error($link)); 


echo"
	<!-- images -->
	";
	$query = "SELECT * FROM $t_exercise_index_images";
	$result = mysqli_query($link, $query);
	if($result !== FALSE){
		// Count rows
		$row_cnt = mysqli_num_rows($result);
		echo"
		<p>$t_exercise_index_images: $row_cnt</p>
		";
	}
	else{
		mysqli_query($link, "CREATE TABLE $t_exercise_index_images(
	  	 exercise_image_id INT NOT NULL AUTO_INCREMENT,
	 	  PRIMARY KEY(exercise_image_id), 
	  	   exercise_image_user_id INT,
	  	   exercise_image_exercise_id INT,
	  	   exercise_image_datetime DATETIME,
	  	   exercise_image_user_ip VARCHAR(250),
	  	   exercise_image_type VARCHAR(250),
	  	   exercise_image_path VARCHAR(250),
	  	   exercise_image_file VARCHAR(250),
	  	   exercise_image_thumb_small VARCHAR(250),
	  	   exercise_image_thumb_medium VARCHAR(250),
	  	   exercise_image_thumb_large VARCHAR(250),
	  	   exercise_image_uniqe_hits INT,
	  	   exercise_image_uniqe_hits_ip_block TEXT)")
		   or die(mysqli_error());

$stram_exercise_index_images = array(
  array('exercise_image_id' => '3','exercise_image_user_id' => '1','exercise_image_exercise_id' => '3','exercise_image_datetime' => '2018-02-18 12:53:12','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/biceps_curl_med_ez_stang','exercise_image_file' => 'biceps_curl_med_ez_stang_3_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '4','exercise_image_user_id' => '1','exercise_image_exercise_id' => '3','exercise_image_datetime' => '2018-02-18 12:53:45','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/biceps_curl_med_ez_stang','exercise_image_file' => 'biceps_curl_med_ez_stang_3_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '5','exercise_image_user_id' => '1','exercise_image_exercise_id' => '4','exercise_image_datetime' => '2018-02-18 13:01:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/bicepscurl_med_hantler','exercise_image_file' => 'bicepscurl_med_hantler_4_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '6','exercise_image_user_id' => '1','exercise_image_exercise_id' => '4','exercise_image_datetime' => '2018-02-18 13:01:07','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/bicepscurl_med_hantler','exercise_image_file' => 'bicepscurl_med_hantler_4_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '7','exercise_image_user_id' => '1','exercise_image_exercise_id' => '2','exercise_image_datetime' => '2018-02-18 20:08:11','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength//nedtrekk_tau','exercise_image_file' => 'nedtrekk_tau_2_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '8','exercise_image_user_id' => '1','exercise_image_exercise_id' => '2','exercise_image_datetime' => '2018-02-18 20:08:16','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength//nedtrekk_tau','exercise_image_file' => 'nedtrekk_tau_2_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '9','exercise_image_user_id' => '1','exercise_image_exercise_id' => '5','exercise_image_datetime' => '2018-02-19 16:55:34','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress','exercise_image_file' => 'benkpress_5_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '10','exercise_image_user_id' => '1','exercise_image_exercise_id' => '5','exercise_image_datetime' => '2018-02-19 16:55:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress','exercise_image_file' => 'benkpress_5_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '13','exercise_image_user_id' => '1','exercise_image_exercise_id' => '7','exercise_image_datetime' => '2018-02-21 17:30:55','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/pull_ups','exercise_image_file' => 'pull_ups_7_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '14','exercise_image_user_id' => '1','exercise_image_exercise_id' => '7','exercise_image_datetime' => '2018-02-21 17:31:00','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/pull_ups','exercise_image_file' => 'pull_ups_7_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '15','exercise_image_user_id' => '1','exercise_image_exercise_id' => '8','exercise_image_datetime' => '2018-02-21 17:45:55','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/armhevninger','exercise_image_file' => 'armhevninger_8_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '16','exercise_image_user_id' => '1','exercise_image_exercise_id' => '8','exercise_image_datetime' => '2018-02-21 17:46:01','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/armhevninger','exercise_image_file' => 'armhevninger_8_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '17','exercise_image_user_id' => '1','exercise_image_exercise_id' => '9','exercise_image_datetime' => '2018-03-10 17:19:31','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/supermann','exercise_image_file' => 'supermann_9_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '18','exercise_image_user_id' => '1','exercise_image_exercise_id' => '9','exercise_image_datetime' => '2018-03-10 17:19:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/supermann','exercise_image_file' => 'supermann_9_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '19','exercise_image_user_id' => '1','exercise_image_exercise_id' => '10','exercise_image_datetime' => '2018-03-10 17:33:00','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/skra_hantlepress','exercise_image_file' => 'skra_hantlepress_10_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '20','exercise_image_user_id' => '1','exercise_image_exercise_id' => '10','exercise_image_datetime' => '2018-03-10 17:33:05','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/skra_hantlepress','exercise_image_file' => 'skra_hantlepress_10_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '21','exercise_image_user_id' => '1','exercise_image_exercise_id' => '11','exercise_image_datetime' => '2018-03-10 18:20:30','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/hantlepress','exercise_image_file' => 'hantlepress_11_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '22','exercise_image_user_id' => '1','exercise_image_exercise_id' => '11','exercise_image_datetime' => '2018-03-10 18:20:34','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/hantlepress','exercise_image_file' => 'hantlepress_11_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '23','exercise_image_user_id' => '1','exercise_image_exercise_id' => '12','exercise_image_datetime' => '2018-03-10 18:29:09','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/sholder/skulderpress_med_hantler','exercise_image_file' => 'skulderpress_med_hantler_12_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '24','exercise_image_user_id' => '1','exercise_image_exercise_id' => '12','exercise_image_datetime' => '2018-03-10 18:29:14','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/sholder/skulderpress_med_hantler','exercise_image_file' => 'skulderpress_med_hantler_12_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '25','exercise_image_user_id' => '1','exercise_image_exercise_id' => '13','exercise_image_datetime' => '2018-03-10 18:36:37','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/kabel_flyes_hoye','exercise_image_file' => 'kabel_flyes_hoye_13_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '26','exercise_image_user_id' => '1','exercise_image_exercise_id' => '13','exercise_image_datetime' => '2018-03-10 18:36:43','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/kabel_flyes_hoye','exercise_image_file' => 'kabel_flyes_hoye_13_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '27','exercise_image_user_id' => '1','exercise_image_exercise_id' => '14','exercise_image_datetime' => '2018-03-10 18:44:32','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/kneboy_med_stang','exercise_image_file' => 'kneboy_med_stang_14_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '28','exercise_image_user_id' => '1','exercise_image_exercise_id' => '14','exercise_image_datetime' => '2018-03-10 18:44:38','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/kneboy_med_stang','exercise_image_file' => 'kneboy_med_stang_14_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '29','exercise_image_user_id' => '1','exercise_image_exercise_id' => '15','exercise_image_datetime' => '2018-03-10 21:44:57','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/markloft_med_hantler','exercise_image_file' => 'markloft_med_hantler_15_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '30','exercise_image_user_id' => '1','exercise_image_exercise_id' => '15','exercise_image_datetime' => '2018-03-10 21:45:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/markloft_med_hantler','exercise_image_file' => 'markloft_med_hantler_15_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '31','exercise_image_user_id' => '1','exercise_image_exercise_id' => '16','exercise_image_datetime' => '2018-03-10 21:51:22','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/sholder/fronthev','exercise_image_file' => 'fronthev_16_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '32','exercise_image_user_id' => '1','exercise_image_exercise_id' => '16','exercise_image_datetime' => '2018-03-10 21:51:27','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/sholder/fronthev','exercise_image_file' => 'fronthev_16_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '33','exercise_image_user_id' => '1','exercise_image_exercise_id' => '17','exercise_image_datetime' => '2018-03-10 23:01:26','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/intervaller_400_m_x_12__1_min_pause','exercise_image_file' => 'intervaller_400_m_x_12__1_min_pause_17_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '34','exercise_image_user_id' => '1','exercise_image_exercise_id' => '18','exercise_image_datetime' => '2018-03-10 23:12:55','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/lett_joggetur','exercise_image_file' => 'lett_joggetur_18_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '35','exercise_image_user_id' => '1','exercise_image_exercise_id' => '19','exercise_image_datetime' => '2018-03-11 09:03:18','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/intervaller_800_m_x_6__2_min_pause','exercise_image_file' => 'intervaller_800_m_x_6__2_min_pause_19_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '36','exercise_image_user_id' => '1','exercise_image_exercise_id' => '20','exercise_image_datetime' => '2018-03-11 09:08:18','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/intervaller_1_6_km_x_3__3_min_pause','exercise_image_file' => 'intervaller_1_6_km_x_3__3_min_pause_20_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '37','exercise_image_user_id' => '1','exercise_image_exercise_id' => '21','exercise_image_datetime' => '2018-03-11 09:12:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/tempo_joggetur','exercise_image_file' => 'tempo_joggetur_21_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '38','exercise_image_user_id' => '1','exercise_image_exercise_id' => '22','exercise_image_datetime' => '2018-03-11 09:30:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/cardio/rompe__lar_og_legger/langkjoring_joggetur','exercise_image_file' => 'langkjoring_joggetur_22_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '39','exercise_image_user_id' => '1','exercise_image_exercise_id' => '23','exercise_image_datetime' => '2018-03-12 16:52:43','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/hammercurl_med_hantler','exercise_image_file' => 'hammercurl_med_hantler_23_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '40','exercise_image_user_id' => '1','exercise_image_exercise_id' => '23','exercise_image_datetime' => '2018-03-12 16:52:49','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/hammercurl_med_hantler','exercise_image_file' => 'hammercurl_med_hantler_23_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '41','exercise_image_user_id' => '1','exercise_image_exercise_id' => '24','exercise_image_datetime' => '2018-03-17 22:19:35','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/markloft_med_stang','exercise_image_file' => 'markloft_med_stang_24_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '42','exercise_image_user_id' => '1','exercise_image_exercise_id' => '24','exercise_image_datetime' => '2018-03-17 22:19:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/markloft_med_stang','exercise_image_file' => 'markloft_med_stang_24_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '43','exercise_image_user_id' => '1','exercise_image_exercise_id' => '25','exercise_image_datetime' => '2018-03-18 08:26:35','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/utfall_med_stang','exercise_image_file' => 'utfall_med_stang_25_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '44','exercise_image_user_id' => '1','exercise_image_exercise_id' => '25','exercise_image_datetime' => '2018-03-18 08:26:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/utfall_med_stang','exercise_image_file' => 'utfall_med_stang_25_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '45','exercise_image_user_id' => '1','exercise_image_exercise_id' => '26','exercise_image_datetime' => '2018-03-18 08:50:23','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/omvendt_roing_i_smithmaskin','exercise_image_file' => 'omvendt_roing_i_smithmaskin_26_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '46','exercise_image_user_id' => '1','exercise_image_exercise_id' => '26','exercise_image_datetime' => '2018-03-18 08:50:27','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/omvendt_roing_i_smithmaskin','exercise_image_file' => 'omvendt_roing_i_smithmaskin_26_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '47','exercise_image_user_id' => '1','exercise_image_exercise_id' => '27','exercise_image_datetime' => '2018-03-18 09:04:23','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/dips','exercise_image_file' => 'dips_27_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '48','exercise_image_user_id' => '1','exercise_image_exercise_id' => '27','exercise_image_datetime' => '2018-03-18 09:04:28','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/dips','exercise_image_file' => 'dips_27_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '49','exercise_image_user_id' => '1','exercise_image_exercise_id' => '28','exercise_image_datetime' => '2018-03-18 09:13:57','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/kabel_flyes_lave','exercise_image_file' => 'kabel_flyes_lave_28_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '50','exercise_image_user_id' => '1','exercise_image_exercise_id' => '28','exercise_image_datetime' => '2018-03-18 09:14:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/kabel_flyes_lave','exercise_image_file' => 'kabel_flyes_lave_28_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '51','exercise_image_user_id' => '1','exercise_image_exercise_id' => '29','exercise_image_datetime' => '2018-03-18 09:30:08','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/crunches','exercise_image_file' => 'crunches_29_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '52','exercise_image_user_id' => '1','exercise_image_exercise_id' => '29','exercise_image_datetime' => '2018-03-18 09:30:13','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/crunches','exercise_image_file' => 'crunches_29_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '53','exercise_image_user_id' => '1','exercise_image_exercise_id' => '30','exercise_image_datetime' => '2018-03-18 09:43:31','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/omvendt_skra_hantlepress','exercise_image_file' => 'omvendt_skra_hantlepress_30_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '54','exercise_image_user_id' => '1','exercise_image_exercise_id' => '30','exercise_image_datetime' => '2018-03-18 09:43:36','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/omvendt_skra_hantlepress','exercise_image_file' => 'omvendt_skra_hantlepress_30_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '55','exercise_image_user_id' => '1','exercise_image_exercise_id' => '31','exercise_image_datetime' => '2018-03-18 15:06:19','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/liggende_tricepspress','exercise_image_file' => 'liggende_tricepspress_31_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '56','exercise_image_user_id' => '1','exercise_image_exercise_id' => '31','exercise_image_datetime' => '2018-03-18 15:06:23','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/liggende_tricepspress','exercise_image_file' => 'liggende_tricepspress_31_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '57','exercise_image_user_id' => '1','exercise_image_exercise_id' => '32','exercise_image_datetime' => '2018-03-18 15:58:17','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/flyes_med_hantler','exercise_image_file' => 'flyes_med_hantler_32_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '58','exercise_image_user_id' => '1','exercise_image_exercise_id' => '32','exercise_image_datetime' => '2018-03-18 15:58:21','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/flyes_med_hantler','exercise_image_file' => 'flyes_med_hantler_32_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '59','exercise_image_user_id' => '1','exercise_image_exercise_id' => '33','exercise_image_datetime' => '2018-03-18 16:08:45','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/utfall_med_hantler','exercise_image_file' => 'utfall_med_hantler_33_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '60','exercise_image_user_id' => '1','exercise_image_exercise_id' => '33','exercise_image_datetime' => '2018-03-18 16:08:49','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/utfall_med_hantler','exercise_image_file' => 'utfall_med_hantler_33_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '61','exercise_image_user_id' => '1','exercise_image_exercise_id' => '34','exercise_image_datetime' => '2018-03-18 16:16:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/sholder/sidehev','exercise_image_file' => 'sidehev_34_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '62','exercise_image_user_id' => '1','exercise_image_exercise_id' => '34','exercise_image_datetime' => '2018-03-18 16:16:44','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/sholder/sidehev','exercise_image_file' => 'sidehev_34_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '63','exercise_image_user_id' => '1','exercise_image_exercise_id' => '35','exercise_image_datetime' => '2018-03-19 21:49:50','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/benspark_leg_extension','exercise_image_file' => 'benspark_leg_extension_35_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '64','exercise_image_user_id' => '1','exercise_image_exercise_id' => '35','exercise_image_datetime' => '2018-03-19 21:49:58','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/benspark_leg_extension','exercise_image_file' => 'benspark_leg_extension_35_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '65','exercise_image_user_id' => '1','exercise_image_exercise_id' => '36','exercise_image_datetime' => '2018-03-20 16:36:49','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/beinpress_leg_press','exercise_image_file' => 'beinpress_leg_press_36_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '66','exercise_image_user_id' => '1','exercise_image_exercise_id' => '36','exercise_image_datetime' => '2018-03-20 16:36:55','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/beinpress_leg_press','exercise_image_file' => 'beinpress_leg_press_36_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '67','exercise_image_user_id' => '1','exercise_image_exercise_id' => '37','exercise_image_datetime' => '2018-03-20 16:47:54','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/franskpress','exercise_image_file' => 'franskpress_37_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '68','exercise_image_user_id' => '1','exercise_image_exercise_id' => '37','exercise_image_datetime' => '2018-03-20 16:47:58','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/franskpress','exercise_image_file' => 'franskpress_37_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '69','exercise_image_user_id' => '1','exercise_image_exercise_id' => '38','exercise_image_datetime' => '2018-03-20 16:54:30','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/larcurl_leg_curl','exercise_image_file' => 'larcurl_leg_curl_38_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '70','exercise_image_user_id' => '1','exercise_image_exercise_id' => '38','exercise_image_datetime' => '2018-03-20 16:54:35','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/larcurl_leg_curl','exercise_image_file' => 'larcurl_leg_curl_38_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '71','exercise_image_user_id' => '1','exercise_image_exercise_id' => '39','exercise_image_datetime' => '2018-03-20 17:03:09','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress_i_maskin','exercise_image_file' => 'benkpress_i_maskin_39_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '72','exercise_image_user_id' => '1','exercise_image_exercise_id' => '39','exercise_image_datetime' => '2018-03-20 17:03:14','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress_i_maskin','exercise_image_file' => 'benkpress_i_maskin_39_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '73','exercise_image_user_id' => '1','exercise_image_exercise_id' => '40','exercise_image_datetime' => '2018-03-20 17:35:55','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/en_arms_bicepscurl_med_hantel','exercise_image_file' => 'en_arms_bicepscurl_med_hantel_40_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '74','exercise_image_user_id' => '1','exercise_image_exercise_id' => '40','exercise_image_datetime' => '2018-03-20 17:36:00','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/en_arms_bicepscurl_med_hantel','exercise_image_file' => 'en_arms_bicepscurl_med_hantel_40_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '75','exercise_image_user_id' => '1','exercise_image_exercise_id' => '41','exercise_image_datetime' => '2018-03-20 17:47:19','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/en_arms_tricepspress_med_hantel','exercise_image_file' => 'en_arms_tricepspress_med_hantel_41_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '76','exercise_image_user_id' => '1','exercise_image_exercise_id' => '41','exercise_image_datetime' => '2018-03-20 17:47:23','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/en_arms_tricepspress_med_hantel','exercise_image_file' => 'en_arms_tricepspress_med_hantel_41_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '77','exercise_image_user_id' => '1','exercise_image_exercise_id' => '1','exercise_image_datetime' => '2018-03-20 18:04:21','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/bulgarsk_utfall','exercise_image_file' => 'bulgarsk_utfall_1_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '78','exercise_image_user_id' => '1','exercise_image_exercise_id' => '1','exercise_image_datetime' => '2018-03-20 18:04:25','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/bulgarsk_utfall','exercise_image_file' => 'bulgarsk_utfall_1_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '79','exercise_image_user_id' => '1','exercise_image_exercise_id' => '42','exercise_image_datetime' => '2018-03-20 18:14:19','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/goblet_squats','exercise_image_file' => 'goblet_squats_42_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '80','exercise_image_user_id' => '1','exercise_image_exercise_id' => '42','exercise_image_datetime' => '2018-03-20 18:14:24','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/goblet_squats','exercise_image_file' => 'goblet_squats_42_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '81','exercise_image_user_id' => '1','exercise_image_exercise_id' => '43','exercise_image_datetime' => '2018-03-20 18:22:59','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/biceps_curl_med_ez_stang_over_benk','exercise_image_file' => 'biceps_curl_med_ez_stang_over_benk_43_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '82','exercise_image_user_id' => '1','exercise_image_exercise_id' => '43','exercise_image_datetime' => '2018-03-20 18:23:04','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/biceps_curl_med_ez_stang_over_benk','exercise_image_file' => 'biceps_curl_med_ez_stang_over_benk_43_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '83','exercise_image_user_id' => '1','exercise_image_exercise_id' => '44','exercise_image_datetime' => '2018-03-20 18:28:50','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/staende_roing_med_stang','exercise_image_file' => 'staende_roing_med_stang_44_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '84','exercise_image_user_id' => '1','exercise_image_exercise_id' => '44','exercise_image_datetime' => '2018-03-20 18:28:56','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/staende_roing_med_stang','exercise_image_file' => 'staende_roing_med_stang_44_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '85','exercise_image_user_id' => '1','exercise_image_exercise_id' => '45','exercise_image_datetime' => '2018-03-20 21:29:23','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/en_arms_roing_med_hantler','exercise_image_file' => 'en_arms_roing_med_hantler_45_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '86','exercise_image_user_id' => '1','exercise_image_exercise_id' => '45','exercise_image_datetime' => '2018-03-20 21:29:28','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/en_arms_roing_med_hantler','exercise_image_file' => 'en_arms_roing_med_hantler_45_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '87','exercise_image_user_id' => '1','exercise_image_exercise_id' => '46','exercise_image_datetime' => '2018-03-20 21:40:44','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sittende_ab_crunches_i_kabel','exercise_image_file' => 'sittende_ab_crunches_i_kabel_46_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '88','exercise_image_user_id' => '1','exercise_image_exercise_id' => '46','exercise_image_datetime' => '2018-03-20 21:40:52','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sittende_ab_crunches_i_kabel','exercise_image_file' => 'sittende_ab_crunches_i_kabel_46_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '89','exercise_image_user_id' => '1','exercise_image_exercise_id' => '47','exercise_image_datetime' => '2018-03-21 17:08:15','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/roing','exercise_image_file' => 'roing_47_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '90','exercise_image_user_id' => '1','exercise_image_exercise_id' => '47','exercise_image_datetime' => '2018-03-21 17:08:21','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/roing','exercise_image_file' => 'roing_47_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '91','exercise_image_user_id' => '1','exercise_image_exercise_id' => '48','exercise_image_datetime' => '2018-03-21 17:20:13','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/sittende_leggcurl','exercise_image_file' => 'sittende_leggcurl_48_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '92','exercise_image_user_id' => '1','exercise_image_exercise_id' => '48','exercise_image_datetime' => '2018-03-21 17:20:18','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/rompe__lar_og_legger/sittende_leggcurl','exercise_image_file' => 'sittende_leggcurl_48_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '93','exercise_image_user_id' => '1','exercise_image_exercise_id' => '49','exercise_image_datetime' => '2018-03-21 17:28:07','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/sholder/shrugs','exercise_image_file' => 'shrugs_49_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '94','exercise_image_user_id' => '1','exercise_image_exercise_id' => '49','exercise_image_datetime' => '2018-03-21 17:28:12','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/sholder/shrugs','exercise_image_file' => 'shrugs_49_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '95','exercise_image_user_id' => '1','exercise_image_exercise_id' => '50','exercise_image_datetime' => '2018-03-21 17:41:37','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sideboy_med_hantel','exercise_image_file' => 'sideboy_med_hantel_50_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '96','exercise_image_user_id' => '1','exercise_image_exercise_id' => '50','exercise_image_datetime' => '2018-03-21 17:41:41','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sideboy_med_hantel','exercise_image_file' => 'sideboy_med_hantel_50_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '97','exercise_image_user_id' => '1','exercise_image_exercise_id' => '51','exercise_image_datetime' => '2018-03-21 17:50:01','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sideplanke','exercise_image_file' => 'sideplanke_51_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '98','exercise_image_user_id' => '1','exercise_image_exercise_id' => '51','exercise_image_datetime' => '2018-03-21 17:50:06','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sideplanke','exercise_image_file' => 'sideplanke_51_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '99','exercise_image_user_id' => '1','exercise_image_exercise_id' => '52','exercise_image_datetime' => '2018-03-21 18:10:13','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress_i_smithmaskin','exercise_image_file' => 'benkpress_i_smithmaskin_52_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '100','exercise_image_user_id' => '1','exercise_image_exercise_id' => '52','exercise_image_datetime' => '2018-03-21 18:10:18','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/chest/benkpress_i_smithmaskin','exercise_image_file' => 'benkpress_i_smithmaskin_52_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '101','exercise_image_user_id' => '1','exercise_image_exercise_id' => '53','exercise_image_datetime' => '2018-03-21 18:16:29','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/other//staende_bicepscurl_med_stang_i_kabel','exercise_image_file' => 'staende_bicepscurl_med_stang_i_kabel_53_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '102','exercise_image_user_id' => '1','exercise_image_exercise_id' => '53','exercise_image_datetime' => '2018-03-21 18:16:34','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/other//staende_bicepscurl_med_stang_i_kabel','exercise_image_file' => 'staende_bicepscurl_med_stang_i_kabel_53_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '103','exercise_image_user_id' => '1','exercise_image_exercise_id' => '54','exercise_image_datetime' => '2018-03-21 18:24:40','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/staende_pushdown_med_boyd_stang','exercise_image_file' => 'staende_pushdown_med_boyd_stang_54_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '104','exercise_image_user_id' => '1','exercise_image_exercise_id' => '54','exercise_image_datetime' => '2018-03-21 18:24:46','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/staende_pushdown_med_boyd_stang','exercise_image_file' => 'staende_pushdown_med_boyd_stang_54_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '105','exercise_image_user_id' => '1','exercise_image_exercise_id' => '55','exercise_image_datetime' => '2018-03-21 18:36:57','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/arms/triceps_nedtrekk_stang_i_kabel','exercise_image_file' => 'triceps_nedtrekk_stang_i_kabel_55_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '106','exercise_image_user_id' => '1','exercise_image_exercise_id' => '55','exercise_image_datetime' => '2018-03-21 18:37:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/arms/triceps_nedtrekk_stang_i_kabel','exercise_image_file' => 'triceps_nedtrekk_stang_i_kabel_55_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '107','exercise_image_user_id' => '1','exercise_image_exercise_id' => '56','exercise_image_datetime' => '2018-03-21 18:47:14','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/nedtrekk_bredt_grep','exercise_image_file' => 'nedtrekk_bredt_grep_56_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '108','exercise_image_user_id' => '1','exercise_image_exercise_id' => '56','exercise_image_datetime' => '2018-03-21 18:47:20','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/nedtrekk_bredt_grep','exercise_image_file' => 'nedtrekk_bredt_grep_56_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '109','exercise_image_user_id' => '1','exercise_image_exercise_id' => '57','exercise_image_datetime' => '2018-03-21 18:58:45','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength//nedtrekk_v-bar','exercise_image_file' => 'nedtrekk_v-bar_57_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '110','exercise_image_user_id' => '1','exercise_image_exercise_id' => '57','exercise_image_datetime' => '2018-03-21 18:58:48','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength//nedtrekk_v-bar','exercise_image_file' => 'nedtrekk_v-bar_57_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '111','exercise_image_user_id' => '1','exercise_image_exercise_id' => '58','exercise_image_datetime' => '2018-03-23 16:30:17','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/liggende_beinhev','exercise_image_file' => 'liggende_beinhev_58_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '112','exercise_image_user_id' => '1','exercise_image_exercise_id' => '58','exercise_image_datetime' => '2018-03-23 16:30:21','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/liggende_beinhev','exercise_image_file' => 'liggende_beinhev_58_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '113','exercise_image_user_id' => '1','exercise_image_exercise_id' => '59','exercise_image_datetime' => '2018-03-23 16:34:13','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/liggende_vekslende_beinhev','exercise_image_file' => 'liggende_vekslende_beinhev_59_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '114','exercise_image_user_id' => '1','exercise_image_exercise_id' => '59','exercise_image_datetime' => '2018-03-23 16:34:17','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/liggende_vekslende_beinhev','exercise_image_file' => 'liggende_vekslende_beinhev_59_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '115','exercise_image_user_id' => '1','exercise_image_exercise_id' => '60','exercise_image_datetime' => '2018-03-23 16:42:11','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/beintrekk','exercise_image_file' => 'beintrekk_60_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '116','exercise_image_user_id' => '1','exercise_image_exercise_id' => '60','exercise_image_datetime' => '2018-03-23 16:42:16','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/beintrekk','exercise_image_file' => 'beintrekk_60_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '117','exercise_image_user_id' => '1','exercise_image_exercise_id' => '61','exercise_image_datetime' => '2018-03-23 16:50:57','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sittende_twists','exercise_image_file' => 'sittende_twists_61_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '118','exercise_image_user_id' => '1','exercise_image_exercise_id' => '61','exercise_image_datetime' => '2018-03-23 16:51:03','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sittende_twists','exercise_image_file' => 'sittende_twists_61_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '119','exercise_image_user_id' => '1','exercise_image_exercise_id' => '62','exercise_image_datetime' => '2018-03-23 16:56:58','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sit-ups','exercise_image_file' => 'sit-ups_62_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '120','exercise_image_user_id' => '1','exercise_image_exercise_id' => '62','exercise_image_datetime' => '2018-03-23 16:57:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/sit-ups','exercise_image_file' => 'sit-ups_62_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '121','exercise_image_user_id' => '1','exercise_image_exercise_id' => '63','exercise_image_datetime' => '2018-03-23 17:02:58','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/hengende_beinhev','exercise_image_file' => 'hengende_beinhev_63_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '122','exercise_image_user_id' => '1','exercise_image_exercise_id' => '63','exercise_image_datetime' => '2018-03-23 17:03:02','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/hengende_beinhev','exercise_image_file' => 'hengende_beinhev_63_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '123','exercise_image_user_id' => '1','exercise_image_exercise_id' => '64','exercise_image_datetime' => '2018-03-23 17:19:44','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/sholder/cross-body_crunch','exercise_image_file' => 'cross-body_crunch_64_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '124','exercise_image_user_id' => '1','exercise_image_exercise_id' => '64','exercise_image_datetime' => '2018-03-23 17:19:50','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/sholder/cross-body_crunch','exercise_image_file' => 'cross-body_crunch_64_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '125','exercise_image_user_id' => '1','exercise_image_exercise_id' => '65','exercise_image_datetime' => '2018-03-23 17:34:04','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/omvendt_skra_crunches','exercise_image_file' => 'omvendt_skra_crunches_65_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '126','exercise_image_user_id' => '1','exercise_image_exercise_id' => '65','exercise_image_datetime' => '2018-03-23 17:34:09','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/omvendt_skra_crunches','exercise_image_file' => 'omvendt_skra_crunches_65_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '127','exercise_image_user_id' => '1','exercise_image_exercise_id' => '66','exercise_image_datetime' => '2018-03-23 17:42:38','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/rollout_med_hjul','exercise_image_file' => 'rollout_med_hjul_66_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '128','exercise_image_user_id' => '1','exercise_image_exercise_id' => '66','exercise_image_datetime' => '2018-03-23 17:42:44','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/rollout_med_hjul','exercise_image_file' => 'rollout_med_hjul_66_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '129','exercise_image_user_id' => '1','exercise_image_exercise_id' => '67','exercise_image_datetime' => '2018-03-23 18:06:41','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/ab_crunches_i_kabel','exercise_image_file' => 'ab_crunches_i_kabel_67_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '130','exercise_image_user_id' => '1','exercise_image_exercise_id' => '67','exercise_image_datetime' => '2018-03-23 18:06:47','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/ab_crunches_i_kabel','exercise_image_file' => 'ab_crunches_i_kabel_67_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '131','exercise_image_user_id' => '1','exercise_image_exercise_id' => '68','exercise_image_datetime' => '2018-03-23 18:12:48','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/stomach/flutter_kicks','exercise_image_file' => 'flutter_kicks_68_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '132','exercise_image_user_id' => '1','exercise_image_exercise_id' => '68','exercise_image_datetime' => '2018-03-23 18:12:52','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/stomach/flutter_kicks','exercise_image_file' => 'flutter_kicks_68_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '133','exercise_image_user_id' => '1','exercise_image_exercise_id' => '69','exercise_image_datetime' => '2018-03-23 18:29:22','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_1','exercise_image_path' => '_uploads/exercises/no/strength/back/rygghev','exercise_image_file' => 'rygghev_69_guide_1.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => ''),
  array('exercise_image_id' => '134','exercise_image_user_id' => '1','exercise_image_exercise_id' => '69','exercise_image_datetime' => '2018-03-23 18:29:27','exercise_image_user_ip' => '81.166.225.197','exercise_image_type' => 'guide_2','exercise_image_path' => '_uploads/exercises/no/strength/back/rygghev','exercise_image_file' => 'rygghev_69_guide_2.png','exercise_image_uniqe_hits' => '0','exercise_image_uniqe_hits_ip_block' => '')
);


		foreach($stram_exercise_index_images as $v){
			
			$exercise_image_user_id = $v["exercise_image_user_id"];
			$exercise_image_exercise_id = $v["exercise_image_exercise_id"];
			$exercise_image_datetime = $v["exercise_image_datetime"];
			$exercise_image_type = $v["exercise_image_type"];
			$exercise_image_path = $v["exercise_image_path"];
			$exercise_image_file = $v["exercise_image_file"];
		
			mysqli_query($link, "INSERT INTO $t_exercise_index_images
			(exercise_image_id, exercise_image_user_id, exercise_image_exercise_id, exercise_image_datetime, exercise_image_type, exercise_image_path, exercise_image_file) 
			VALUES 
			(NULL, '$exercise_image_user_id', '$exercise_image_exercise_id', '$exercise_image_datetime', '$exercise_image_type', '$exercise_image_path', 
			'$exercise_image_file')
			")
			or die(mysqli_error($link));


		}



	}
	echo"
	<!-- //images -->

";
?>